#!/usr/bin/env bash
# Script to install nginx on server

sudo apt-get update -y
sudo apt-get install nginx -y
sudo echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
redirectme="server_name _;\n\trewrite ^\/redirect_me google.com permanent;"
sudo sed -i "s/server_name _;/$redirectme/" /etc/nginx/sites-enabled/default
sudo /etc/init.d/nginx start
sudo /etc/init.d/nginx restart
