#!/usr/bin/env bash
# configures Nginx server so that /redirect_me redirects to other page


sudo apt-get update
sudo apt-get install -y nginx
echo -e "Ceci n'est pas une page\n" | sudo tee /usr/share/nginx/html/404.html
file="/etc/nginx/sites-enabled/default"
new_string="error_page 404 \/404.html;"
sudo sed -i "26i $new_string" $file
sudo service nginx start
