#!/usr/bin/env bash
#find out s keeping your Ubuntu's
#Nginx installation from listening on port 80

sudo apt-get update
sudo apt-get -y install nginx
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx start
