#!/usr/bin/env bash
#script that loops from 1 to 10 and displays bad luck, good luck, and Holberton school respectively on 4, 8, the rest

counter=1
while [ $counter -le 10 ]
do
	if [ $counter -eq 4 ]
	then
		echo "bad luck"
	elif [ $counter -eq 8 ]
	then
	     echo "good luck"
	else
		echo "Holberton School"
	fi
	((counter++))
done